apiVersion: apps/v1
kind: Deployment
metadata:
  name: executors-hybrid-executors-apply
  namespace: ${tobiko_namespace}

  labels:
    app.kubernetes.io/instance: executors
    app.kubernetes.io/name: hybrid-executors
    app.kubernetes.io/component: apply-executor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: executors
      app.kubernetes.io/name: hybrid-executors
      app.kubernetes.io/component: apply-executor
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: executors
        app.kubernetes.io/name: hybrid-executors
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: apply-executor
    spec:
      # serviceAccountName: default
      containers:
        - name: apply-executor
          image: "tobikodata/tcloud:latest"
          imagePullPolicy: "Always"
          args:
            - "executor"
            - "apply"
          env:
            - name: TCLOUD_URL
              valueFrom:
                secretKeyRef:
                  name: executors-hybrid-executors-secrets
                  key: TCLOUD_URL
            - name: TCLOUD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: executors-hybrid-executors-secrets
                  key: TCLOUD_CLIENT_ID
            - name: TCLOUD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: executors-hybrid-executors-secrets
                  key: TCLOUD_CLIENT_SECRET
            - name: SQLMESH__DEFAULT_GATEWAY
              value: "databricks"
            - name: SQLMESH__GATEWAYS__DATABRICKS__CONNECTION__CATALOG
              value: "rde_development"
            - name: SQLMESH__GATEWAYS__DATABRICKS__CONNECTION__SERVER_HOSTNAME
              value: "adb-373128615800175.15.azuredatabricks.net"
            - name: SQLMESH__GATEWAYS__DATABRICKS__CONNECTION__HTTP_PATH
              value: "/sql/1.0/warehouses/4f4e66bc9587aff1"
            - name: SQLMESH__GATEWAYS__DATABRICKS__CONNECTION__ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: executors-hybrid-executors-secrets
                  key: SQLMESH__GATEWAYS__DATABRICKS__CONNECTION__ACCESS_TOKEN
            - name: SQLMESH__GATEWAYS__DATABRICKS__CONNECTION__TYPE
              value: "databricks"
          # readinessProbe:
          #   exec:
          #     command:
          #       - /app/pex
          #       - executor
          #       - apply
          #       - --check
          #   initialDelaySeconds: 0
          #   periodSeconds: 10
          #   timeoutSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: 10Gi
              memory: 4Gi
            requests:
              cpu: "1"
              ephemeral-storage: 10Gi
              memory: 2Gi